version: '3.8'

services:
  web:
    build: .
    platform: linux/amd64
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:10.5
    restart: always
    environment:
      MARIADB_DATABASE: ratforum
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  db-init:
    image: mariadb:10.5
    depends_on:
      - db
    volumes:
      - ./init.sql:/init.sql
    entrypoint: ["sh", "-c", "sleep 10 && mysql -h db -u root -proot < /init.sql"]

  phpmyadmin:
    image: phpmyadmin:5.2.1
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data:
